// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhetnibrhizggympnqrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZXRuaWJyaGl6Z2d5bXBucXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTMyOTcsImV4cCI6MjA2OTgyOTI5N30.OXGcdtpjSx_zw1GKDbH-QYJckm_5qYEl3g5ng20uwQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});